version: '5.0'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: jesus
      MONGO_INITDB_ROOT_PASSWORD: krowdy123